=== codenitrr/nordcraft/packages/lib/schemas/libFormula.schema.json
{
  "$id": "libFormula.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Lib formula",
  "description": "A builtin formula in the Nordcraft runtime",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "minLength": 1
    },
    "description": {
      "type": "string",
      "minLength": 1
    },
    "mdnUrl": {
      "type": "string"
    },
    "arguments": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": { "type": "string", "minLength": 1 },
          "description": { "type": "string", "minLength": 1 },
          "type": { "type": "object" },
          "formula": { "$ref": "/Formula" }
        },
        "required": ["name", "type"]
      }
    },
    "output": {
      "type": "object",
      "properties": {
        "description": { "type": "string", "minLength": 1 }
      }
    }
  },
  "required": ["name", "description"],
  "additionalProperties": true
}

=== codenitrr/nordcraft/packages/lib/formulas/roundDown/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "Round down",
  "description": "Round a Number down to the nearest decimal point.",
  "arguments": [
    {
      "name": "Input",
      "description": "Number to round down.",
      "type": {
        "type": "Number"
      },
      "formula": {
        "type": "value",
        "value": 1
      }
    },
    {
      "name": "Decimals",
      "description": "Number of decimals to round to.",
      "type": {
        "type": "Number"
      },
      "formula": {
        "type": "value",
        "value": 0
      }
    }
  ],
  "output": {
    "type": {
      "type": "Number"
    },
    "description": "The rounded Number."
  },
  "mdnUrl": ""
}

=== codenitrr/nordcraft/packages/lib/formulas/canShare/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "Can Share",
  "description": "Return a Boolean indicating whether the provided data can be shared (with the \"Share\" action).",
  "arguments": [
    {
      "name": "URL",
      "description": "The URL you want to check.",
      "type": {
        "type": "String"
      },
      "formula": {
        "type": "value",
        "value": null
      }
    },
    {
      "name": "Title",
      "description": "The title you want to check.",
      "type": {
        "type": "String"
      },
      "formula": {
        "type": "value",
        "value": null
      }
    },
    {
      "name": "Text",
      "description": "The text you want to check.",
      "type": {
        "type": "String"
      },
      "formula": {
        "type": "value",
        "value": null
      }
    }
  ],
  "mdnUrl": ""
}

=== codenitrr/nordcraft/packages/lib/formulas/string/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "String",
  "description": "Convert a value of any type to a String.",
  "arguments": [
    {
      "name": "Input",
      "description": "Value of any type.",
      "type": {
        "type": "Any"
      },
      "formula": {
        "type": "value",
        "value": "1"
      }
    }
  ],
  "output": {
    "description": "The input value converted to a String",
    "type": {
      "type": "String"
    }
  },
  "mdnUrl": ""
}

=== codenitrr/nordcraft/packages/lib/formulas/deleteKey/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "Delete",
  "description": "Return a copy of the input Object or Array without the specified key.",
  "arguments": [
    {
      "name": "Object",
      "formula": {
        "type": "value",
        "value": null
      },
      "description": "The input record.",
      "type": {
        "type": "Array \\| Object"
      }
    },
    {
      "name": "Path",
      "formula": {
        "type": "value",
        "value": "Item"
      },
      "description": "The path can be either a Number (if the first argument is an array), a String, or an Array of strings. If an Array is given, the property at that path will be removed.",
      "type": {
        "type": "Array<Number \\| String> \\| Number \\| String"
      }
    }
  ],
  "output": {
    "description": "A copy of the record without the property specified in the Path.",
    "type": {
      "type": "Object"
    }
  },
  "mdnUrl": ""
}

=== codenitrr/nordcraft/packages/lib/formulas/isServer/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "Is Server",
  "description": "Get information about whether formulas are currently evaluated server-side or client-side.",
  "arguments": [],
  "output": {
    "description": "Returns True if formulas are evaluated server-side, and False if formulas are evaluated client-side.",
    "type": {
      "type": "Boolean"
    }
  },
  "mdnUrl": ""
}

=== codenitrr/nordcraft/packages/lib/formulas/get/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "Get",
  "description": "Extract a value from an Object, Array or String at the specified path.",
  "arguments": [
    {
      "name": "Object",
      "formula": {
        "type": "value",
        "value": null
      },
      "description": "The Object, Array or String you want to extract an item from.",
      "type": {
        "type": "Array \\| Object \\| String"
      }
    },
    {
      "name": "Path",
      "formula": {
        "type": "value",
        "value": "Item"
      },
      "description": "The Path can be either a Number, a String, or an Array.",
      "type": {
        "type": "Array<String> \\| Number \\| String"
      }
    }
  ],
  "output": {
    "description": "The value found at the Path. If no value is found, this value of the output is Null.",
    "type": {
      "type": "Any"
    }
  },
  "mdnUrl": ""
}

=== codenitrr/nordcraft/packages/lib/formulas/timestamp/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "Timestamp",
  "description": "Get the timestamp from a Date, e.g. 1633462980000.",
  "arguments": [
    {
      "name": "Date",
      "description": "The date to get the timestamp from.",
      "type": {
        "type": "Date"
      },
      "formula": {
        "type": "value",
        "value": null
      }
    }
  ],
  "output": {
    "description": "The timestamp from the date input.",
    "type": {
      "type": "Number"
    }
  },
  "mdnUrl": ""
}

=== codenitrr/nordcraft/packages/lib/formulas/lessOrEqual/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "Less or equal",
  "description": "Compute if a value is smaller than or equal to another value.",
  "arguments": [
    {
      "name": "First",
      "formula": {
        "type": "value",
        "value": ""
      },
      "description": "First Number to be compared.",
      "type": {
        "type": "Number"
      }
    },
    {
      "name": "Second",
      "formula": {
        "type": "value",
        "value": ""
      },
      "description": "Second Number to be compared.",
      "type": {
        "type": "Number"
      }
    }
  ],
  "output": {
    "description": "Returns True if the First Number is smaller than or equal to the second Number, otherwise it returns False.",
    "type": {
      "type": "Boolean"
    }
  },
  "mdnUrl": ""
}
