=== codenitrr/nordcraft/packages/lib/schemas/libFormula.schema.json
{
  "$id": "libFormula.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Lib formula",
  "description": "A builtin formula in the Nordcraft runtime",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "minLength": 1
    },
    "description": {
      "type": "string",
      "minLength": 1
    },
    "mdnUrl": {
      "type": "string"
    },
    "arguments": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": { "type": "string", "minLength": 1 },
          "description": { "type": "string", "minLength": 1 },
          "type": { "type": "object" },
          "formula": { "$ref": "/Formula" }
        },
        "required": ["name", "type"]
      }
    },
    "output": {
      "type": "object",
      "properties": {
        "description": { "type": "string", "minLength": 1 }
      }
    }
  },
  "required": ["name", "description"],
  "additionalProperties": true
}

=== codenitrr/nordcraft/packages/lib/formulas/not/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "Not",
  "description": "Get the Boolean opposite of an input value.",
  "arguments": [
    {
      "name": "Input",
      "formula": {
        "type": "value",
        "value": true
      },
      "description": "The input value.",
      "type": {
        "type": "Boolean"
      }
    }
  ],
  "output": {
    "description": "Returns True if the input value is False, and False if the input value is True.",
    "type": {
      "type": "Boolean"
    }
  },
  "mdnUrl": ""
}

=== codenitrr/nordcraft/packages/lib/formulas/size/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "Size",
  "description": "Get the size of an Array, Object or String.",
  "arguments": [
    {
      "name": "Collection",
      "formula": {
        "type": "value",
        "value": [
          1,
          2,
          3
        ]
      },
      "description": "The collection to get the size of.",
      "type": {
        "type": "Array \\| Object \\| String"
      }
    }
  ],
  "output": {
    "description": "The size of the collection.",
    "type": {
      "type": "Number"
    }
  },
  "mdnUrl": ""
}

=== codenitrr/nordcraft/packages/lib/formulas/lessThan/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "Less than",
  "description": "Compute if a value is smaller than another value.",
  "arguments": [
    {
      "name": "First",
      "formula": {
        "type": "value",
        "value": ""
      },
      "description": "First Number to be compared.",
      "type": {
        "type": "Number"
      }
    },
    {
      "name": "Second",
      "formula": {
        "type": "value",
        "value": ""
      },
      "description": "Second Number to be compared.",
      "type": {
        "type": "Number"
      }
    }
  ],
  "output": {
    "description": "Returns True if the First Number is smaller than the second Number, otherwise it returns False.",
    "type": {
      "type": "Boolean"
    }
  },
  "mdnUrl": ""
}

=== codenitrr/nordcraft/packages/lib/formulas/dateFromTimestamp/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "Date From Timestamp",
  "arguments": [
    {
      "name": "Timestamp",
      "description": "A Number in milliseconds since 1st January, 1970 (EPOCH).",
      "type": {
        "type": "Number"
      },
      "formula": {
        "type": "value",
        "value": 1687787245933
      }
    }
  ],
  "description": "Convert a timestamp (milliseconds) to a Date.",
  "output": {
    "description": "The input value converted to a Date.",
    "type": {
      "type": "Date"
    }
  },
  "mdnUrl": ""
}

=== codenitrr/nordcraft/packages/lib/formulas/last/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "Last",
  "description": "Get the last item in an Array.",
  "arguments": [
    {
      "name": "Array",
      "formula": {
        "type": "value",
        "value": []
      },
      "type": {
        "type": "Array"
      },
      "description": "The input Array."
    }
  ],
  "output": {
    "description": "The last item in the Array.",
    "type": {
      "type": "Any"
    }
  },
  "mdnUrl": ""
}

=== codenitrr/nordcraft/packages/lib/formulas/takeLast/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "Take last",
  "description": "Take items from the end of an Array or String.",
  "arguments": [
    {
      "name": "Array",
      "formula": {
        "type": "value",
        "value": null
      },
      "description": "The input value.",
      "type": {
        "type": "Array \\| String"
      }
    },
    {
      "name": "Count",
      "formula": {
        "type": "value",
        "value": 1
      },
      "description": "Number of items to take.",
      "type": {
        "type": "Number"
      }
    }
  ],
  "output": {
    "description": "The last items from the Array or String.",
    "type": {
      "type": "Array \\| String"
    }
  },
  "mdnUrl": ""
}

=== codenitrr/nordcraft/packages/lib/formulas/groupBy/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "Group by",
  "description": "Group an Array of items into an Object based on a grouping formula.",
  "arguments": [
    {
      "name": "Array",
      "formula": {
        "type": "value",
        "value": null
      },
      "description": "Array of items to be grouped.",
      "type": {
        "type": "Array"
      }
    },
    {
      "name": "Formula",
      "isFunction": true,
      "formula": {
        "type": "value",
        "value": null
      },
      "description": "The grouping formula used to group the items. The String returned from the formula will match the key in the output Oject.",
      "type": {
        "type": "Formula"
      }
    }
  ],
  "output": {
    "description": "An Object where each key matches a value returned by the grouping formula, and each value is the list of items that share the return value.",
    "type": {
      "type": "Object"
    }
  },
  "mdnUrl": ""
}

=== codenitrr/nordcraft/packages/lib/formulas/sum/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "Sum",
  "description": "Return the sum of an Array of numbers.",
  "arguments": [
    {
      "name": "Array",
      "type": {
        "type": "Array"
      },
      "description": "The array of numbers to sum.",
      "formula": {
        "type": "array",
        "arguments": []
      }
    }
  ],
  "output": {
    "description": "The total sum from adding all the numbers in the Array.",
    "type": {
      "type": "Number"
    }
  },
  "mdnUrl": ""
}
