=== codenitrr/nordcraft/packages/lib/schemas/libFormula.schema.json
{
  "$id": "libFormula.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Lib formula",
  "description": "A builtin formula in the Nordcraft runtime",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "minLength": 1
    },
    "description": {
      "type": "string",
      "minLength": 1
    },
    "mdnUrl": {
      "type": "string"
    },
    "arguments": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": { "type": "string", "minLength": 1 },
          "description": { "type": "string", "minLength": 1 },
          "type": { "type": "object" },
          "formula": { "$ref": "/Formula" }
        },
        "required": ["name", "type"]
      }
    },
    "output": {
      "type": "object",
      "properties": {
        "description": { "type": "string", "minLength": 1 }
      }
    }
  },
  "required": ["name", "description"],
  "additionalProperties": true
}

=== codenitrr/nordcraft/packages/lib/formulas/boolean/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "Boolean",
  "description": "Convert a value of any type to a Boolean.",
  "mdnUrl": "",
  "arguments": [
    {
      "name": "Input",
      "description": "Value of any type.",
      "type": { "type": "Any" },
      "formula": { "type": "value", "value": "1" }
    }
  ],
  "output": {
    "description": "The input value converted to a Boolean. False and Null will return False, all other values will return True.",
    "type": { "type": "Boolean" }
  }
}

=== codenitrr/nordcraft/packages/lib/formulas/equals/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "Equals",
  "description": "Compute if values are identical.",
  "arguments": [
    {
      "name": "First",
      "formula": {
        "type": "value",
        "value": ""
      },
      "description": "First Value",
      "type": {
        "type": "Any"
      }
    },
    {
      "name": "Second",
      "formula": {
        "type": "value",
        "value": ""
      },
      "description": "Second Value",
      "type": {
        "type": "Any"
      }
    }
  ],
  "output": {
    "description": "Returns True if the input values are identical, otherwise False.",
    "type": {
      "type": "Boolean"
    }
  },
  "mdnUrl": ""
}

=== codenitrr/nordcraft/packages/lib/formulas/range/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "Range",
  "description": "Create an Array of numbers between a Min and Max value.",
  "arguments": [
    {
      "formula": {
        "type": "value",
        "value": 0
      },
      "name": "Min",
      "description": "The smallest value in the list.",
      "type": {
        "type": "Number"
      }
    },
    {
      "name": "Max",
      "formula": {
        "type": "value",
        "value": 10
      },
      "description": "The largest value in the list.",
      "type": {
        "type": "Number"
      }
    }
  ],
  "output": {
    "description": "An Array containing all the numbers between Min and Max, inclusive.",
    "type": {
      "type": "Array"
    }
  },
  "mdnUrl": ""
}

=== codenitrr/nordcraft/packages/lib/formulas/modulo/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "Modulo",
  "description": "Get the remainder when dividing two Numbers.",
  "arguments": [
    {
      "name": "Dividend",
      "formula": {
        "type": "value",
        "value": 1
      },
      "description": "The number to be divided.",
      "type": {
        "type": "Number"
      }
    },
    {
      "name": "Divider",
      "formula": {
        "type": "value",
        "value": 1
      },
      "description": "The number to divide by.",
      "type": {
        "type": "Number"
      }
    }
  ],
  "output": {
    "description": "The remainder when the Dividend is divided by the Divider.",
    "type": {
      "type": "Number"
    }
  },
  "mdnUrl": ""
}

=== codenitrr/nordcraft/packages/lib/formulas/findLast/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "Find Last",
  "description": "Search through an Array of items and apply a formula to each item, to return the last item where the formula returns True.",
  "arguments": [
    {
      "name": "Array",
      "formula": {
        "type": "value",
        "value": null
      },
      "description": "The array to search.",
      "type": {
        "type": "Array"
      }
    },
    {
      "name": "Formula",
      "isFunction": true,
      "formula": {
        "type": "path",
        "path": [
          "Args",
          "item"
        ]
      },
      "description": "The predicate formula that each item in the Array is passed to.",
      "type": {
        "type": "Formula"
      }
    }
  ],
  "output": {
    "description": "The last item in the Array where the formula returns True. Returns Null if the predicate formula did not return True for any item.",
    "type": {
      "type": "Any"
    }
  },
  "mdnUrl": ""
}

=== codenitrr/nordcraft/packages/lib/formulas/capitalize/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "Capitalize",
  "description": "Capitalize a string: make the first letter uppercase whilst keeping the rest lowercase.",
  "arguments": [
    {
      "name": "String",
      "formula": {
        "type": "value",
        "value": "string"
      },
      "description": "An input String.",
      "type": {
        "type": "String"
      }
    }
  ],
  "output": {
    "description": "The capitalized String.",
    "type": {
      "type": "String"
    }
  },
  "mdnUrl": ""
}

=== codenitrr/nordcraft/packages/lib/formulas/greaterOrEqueal/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "Greater or equal",
  "description": "Compute whether a value is larger than or equal to another value.",
  "arguments": [
    {
      "name": "First",
      "formula": {
        "type": "value",
        "value": ""
      },
      "description": "First value to be compared.",
      "type": {
        "type": "Number"
      }
    },
    {
      "name": "Second",
      "formula": {
        "type": "value",
        "value": ""
      },
      "description": "Second value to be compared.",
      "type": {
        "type": "Number"
      }
    }
  ],
  "output": {
    "description": "Returns True if the first Number is larger than or equal to the second Number.",
    "type": {
      "type": "Boolean"
    }
  },
  "mdnUrl": ""
}

=== codenitrr/nordcraft/packages/lib/formulas/branchName/formula.json
{
  "$schema": "../../schemas/libFormula.schema.json",
  "name": "Branch Name",
  "description": "Get the name of the current branch. For production, the branch name is 'main'.",
  "arguments": [],
  "output": {
    "description": "Returns the name of the current branch.",
    "type": {
      "type": "String"
    }
  },
  "mdnUrl": ""
}
